/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */

allprojects {
    group = "polar.study"

    repositories {
        jcenter()
    }

    buildscript {
        ext["bootVersion"] = "2.1.4.RELEASE"
    }

    tasks {
        register("hello") {
            println("- polar!")
            doFirst {
                println("> started to say HELLO! ${this.project.name}")
            }
        }
    }
}

subprojects {
    version = "0.1.0"
}