server:
  servlet:
    context-path: "/web"
  port: 8090

spring:
  profiles:
    active: local
  redis: ## Spring Redis 설정
    host: localhost
    port: 6379
  session:
    store-type: redis
    redis.namespace: spring:session