spring:
  session:
    store-type: redis
    redis:
      namespace: mono:session

  redis:
    port: 6379
    host: localhost

server:
  servlet:
    session:
      cookie:
        name: POLARID
        path: /
  port: 8001