# Common
server:
  servlet:
    context-path: /mono

spring:
  profiles:
    active: dev

polar:
  env:
    foo: common

---
# Local

spring:
  profiles:
    - local

polar:
  env:
    foo: local

---
# dev

spring:
  profiles:
    - dev

polar:
  env:
    foo: dev
