# Common

server:
  servlet:
    context-path: /mono

spring:
  profiles:
    active: local

---
# Embeded redis
spring:
  profiles: embeded-redis
  session:
#    store-type: redis

  redis:
    port: 16379
---
# Local

spring:
  profiles:
    - local

---
# dev

spring:
  profiles:
    - dev
