version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker/data/redis:/data
    command: ["redis-server",  "--appendonly",  "yes"]
    restart: always